version: "3"
services:
  archipe-dock:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    env_file:
      - .env
    restart: always
    image: archipela-dock
    networks:
      - traefik_frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.archipela-dock.rule=Host(`archipel-uqac.otchi.ovh`)
      - traefik.http.routers.archipela-dock.entrypoints=web
      - traefik.http.routers.archipela-dock-https.rule=Host(`archipel-uqac.otchi.ovh`)
      - traefik.http.routers.archipela-dock-https.entrypoints=websecure
      - traefik.http.routers.archipela-dock-https.tls=true
      - traefik.http.routers.archipela-dock-https.tls.certresolver=ovhcloud

networks:
  traefik_frontend:
